### ISSUE TITLE
kind of questions 

### ISSUE THREAD

**Issue by dragonxtek** [backyardbiomech/qtiConverter#2]
Could you add more kind of questions for Canvas like:

- True/False
- Question with file upload
- Formula question

Is it possible add comments to each response to give feedback to the student?

**Comment by backyardbiomech** [comment]
True/False is can be asked as a multiple choice question with just those two options.

I've started working on formula questions, but haven't gotten it to work yet. I do not foresee adding file upload questions.

I can look into comments for feedback, and may have use for it later this summer.
