### ISSUE TITLE
can't run the program

### ISSUE THREAD

**Issue by jimmychang2018** [backyardbiomech/qtiConverter#4]
When I follow the instruction to download the zip file then unzip and move to desktop, and I prepare the question move to the top of the app icon, then the error message comes out as image show blow  
<img width="854" alt="WeChat1e0fb900f7a3b863113ebdcd709b1eb8" src="https://user-images.githubusercontent.com/40483721/80667735-8bb6ce00-8ad2-11ea-9b65-f58f8a72ea0f.png">
what should i do next?

**Comment by backyardbiomech** [comment]
Try with bank1.txt (found in testfiles/simpleTestForImport/bank1.txt). If that works, then the problem is with the formatting of the question bank you are using. The docs outline the  most common problems to look for.
